# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Run The Borough Borders
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Running London. London Boroughs. Run London. Marathon. Ultra Marathon. 10km. Adventure. London. Run.
  Kingston_upon_Thames.
  Croydon.
  Bromley.
  Hounslow.
  Ealing.
  Havering.
  Hillingdon.
  Harrow.
  Brent.
  Barnet.
  Lewisham.
  Greenwich.
  Bexley.
  Enfield.
  Waltham_Forest.
  Lambeth.
  Redbridge.
  Sutton.
  Richmond_upon_Thames.
  Merton.
  Wandsworth.
  Hammersmith_and_Fulham.
  Southwark.
  Kensington_and_Chelsea.
  City_of_London.
  Westminster.
  Camden.
  Tower_Hamlets.
  Islington.
  Hackney.
  Haringey.
  Newham.
  Barking_and_Dagenham.
baseurl: "/boroughbordersblog" # the subpath of your site, e.g. /blog
url: "https://john-mark-long.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings

plugins:
  - jekyll-feed
  - jekyll-sass-converter

sass:
  style: compressed


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
